# Generated by Django 4.2.3 on 2023-08-27 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLigaDeFutbol', '0003_rename_director_tecnico_directortecnico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='promedio',
            field=models.IntegerField(default=80, validators=[django.core.validators.MaxValueValidator(100, 'Asegúrese de ingresar un valor menor o igual a 100'), django.core.validators.MinValueValidator(0, 'Asegúrese de ingresar un valor mayor o igual a 0')]),
        ),
    ]
