# Generated by Django 4.2.3 on 2023-08-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLigaDeFutbol', '0004_alter_jugador_promedio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='promedio',
            field=models.IntegerField(default=80),
        ),
    ]
