# Generated by Django 4.2.3 on 2023-08-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLigaDeFutbol', '0006_alter_jugador_promedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='transferible',
            field=models.CharField(choices=[('no', 'No'), ('si', 'Si')], default='no', max_length=10, verbose_name='Transferible'),
        ),
    ]
