# Generated by Django 4.2.3 on 2023-09-02 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppLigaDeFutbol', '0007_jugador_transferible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(max_length=60)),
                ('monto_ofrecido', models.IntegerField(verbose_name='Monto ofrecido (U$D)')),
                ('jugador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='AppLigaDeFutbol.jugador')),
            ],
        ),
    ]
