# Generated by Django 4.2.3 on 2023-09-03 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLigaDeFutbol', '0009_jugador_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='fecha_oferta',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
