# Generated by Django 4.2.3 on 2023-09-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLigaDeFutbol', '0011_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='imagen_jugador',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img/jugadores'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img/avatares'),
        ),
    ]
