# Generated by Django 4.2.3 on 2023-09-07 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppLigaDeFutbol', '0013_remove_jugador_imagen_jugador_jugador_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='imagen',
        ),
        migrations.CreateModel(
            name='ImagenJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='assets/img/jugadores')),
                ('jugador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppLigaDeFutbol.jugador')),
            ],
        ),
    ]
