# Generated by Django 4.2.3 on 2023-09-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLigaDeFutbol', '0015_jugador_imagen_delete_imagenjugador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
