# Generated by Django 4.2.3 on 2023-09-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLigaDeFutbol', '0016_alter_jugador_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img/jugadores'),
        ),
    ]
