# Generated by Django 4.2.3 on 2023-09-14 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLigaDeFutbol', '0017_alter_jugador_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
