# Generated by Django 4.2.3 on 2023-09-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLigaDeFutbol', '0018_delete_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='estado',
            field=models.CharField(choices=[('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('no_contestada', 'No Contestada')], default='no_contestada', max_length=13),
        ),
    ]
