# Generated by Django 5.1.5 on 2025-01-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLigaDeFutbol', '0020_oferta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
