# Generated by Django 5.1.5 on 2025-01-23 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLigaDeFutbol', '0021_jugador_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='DirectorTecnico',
        ),
    ]
