# Generated by Django 5.1.5 on 2025-01-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLigaDeFutbol', '0023_donacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='telefono',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donacion',
            name='propietario',
            field=models.CharField(default=3, max_length=90),
            preserve_default=False,
        ),
    ]
