# Generated by Django 5.1.5 on 2025-01-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLigaDeFutbol', '0024_donacion_telefono_alter_donacion_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='contraseña',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
