# Generated by Django 5.1.5 on 2025-01-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLigaDeFutbol', '0026_alter_donacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img/donaciones'),
        ),
    ]
