# Generated by Django 5.1.5 on 2025-02-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLigaDeFutbol', '0027_alter_donacion_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacion',
            name='contraseña',
        ),
        migrations.AddField(
            model_name='donacion',
            name='contrasenia',
            field=models.CharField(default=123, max_length=50, verbose_name='Contraseña'),
            preserve_default=False,
        ),
    ]
