# Generated by Django 5.1.5 on 2025-02-20 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLigaDeFutbol', '0028_remove_donacion_contraseña_donacion_contrasenia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Oferta',
        ),
    ]
