# Generated by Django 5.1.5 on 2025-02-20 20:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=90)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='assets/img/donaciones')),
                ('propietario', models.CharField(max_length=90)),
                ('telefono', models.IntegerField()),
                ('contrasenia', models.CharField(max_length=50, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('posicion', models.CharField(max_length=40)),
                ('promedio', models.IntegerField(default=80, validators=[django.core.validators.MaxValueValidator(100, 'Asegúrese de ingresar un valor menor o igual a 100'), django.core.validators.MinValueValidator(0, 'Asegúrese de ingresar un valor mayor o igual a 0')])),
                ('pierna_habil', models.CharField(max_length=40)),
                ('transferible', models.CharField(choices=[('no', 'No'), ('si', 'Si')], default='no', max_length=10, verbose_name='Transferible')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='assets/img/jugadores')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
