# Generated by Django 5.1.5 on 2025-04-02 18:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('titulo', models.CharField(max_length=90)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='assets/img/donaciones')),
                ('propietario', models.CharField(max_length=90)),
                ('telefono', models.IntegerField()),
                ('contrasenia', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
        ),
    ]
